version: '3.11'
services:
  dbapp:
    build: ./dbapp
    ports:
      - "5001:5001"
    volumes:
      - ./db_data:/app/data
  webapp:
    build: ./webapp
    ports:
      - "5000:5000"
    depends_on:
      - dbapp
    volumes:
      - ./model:/model
volumes:
  db_data:
